version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: cinepass_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  cinepass:
    build: .
    container_name: cinepass_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - MONGO_URI=mongodb://mongo:27017/cinepass_db
    command: gunicorn -b 0.0.0.0:5000 app:app

volumes:
  mongo_data:
