version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      - MONGO_URI=mongodb://db:27017/cinepass
      - REDIS_URL=redis://redis:6379/0

  db:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"

volumes:
  mongo_data:

